spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: create-drop
    show-sql: false
redis:
  host: localhost
  port: 6379

jwt:
  secret:
    key: "testSecretKeyForJWT"

logging:
  level:
    root: WARN
    org.hibernate.SQL: DEBUG